AWSTemplateFormatVersion: 2010-09-09
Description: testing

Parameters:
  App:
    Type: String
    Default: 'Test'

Resources:
  TestPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
    - PolicyDocument:
        Statement:
          - Action:
              - s3:Get*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - 'com-gu-gap'